name: stripe_sdk
description: The only native Stripe library for Flutter. Has complete support for SCA/PSD2, payment intents and the newest Stripe features.
version: 5.0.0-nullsafety.1
homepage: https://github.com/ezet/stripe_sdk

environment:
  sdk: '>=2.13.0 <3.0.0'
  flutter: "^3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.5
  url_launcher: ^6.1.6
  mask_text_input_formatter: ^2.4.0
  simple_animations: ^4.0.1
  awesome_card: ^1.1.7
  credit_card_validator: ^2.0.1
  collection: ^1.16.0
  webview_flutter: ^3.0.2
  universal_html: ^2.0.8


dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

false_secrets:
  - example/**
